name: Build and publish packages
on:
  push:
    tags:
      - "v*"
      # Test workflow without atrifacts publication
      - "test-release-*"

env:
  CARGO_TERM_COLOR: always


jobs:

  release-crate:
    name: Release crate
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.62.1
          profile: minimal
          override: true
          fetch-depth: 5
          submodules: recursive

      - name: Show package contents
        run: |
          cd cli && cargo package --list --allow-dirty

      - name: Build package and publish the crate to crates.io
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          cd cli && cargo publish --token=${{ secrets.CRATES_TOKEN }}
